"""create_games_and_moves_tables

Revision ID: ad9e3bef5ec1
Revises: 
Create Date: 2026-07-28 20:35:21.846388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9e3bef5ec1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fen_atual', sa.Text(), nullable=False),
    sa.Column('turno', sa.String(length=10), nullable=False),
    sa.Column('lado_jogador_branco', sa.String(length=36), nullable=False),
    sa.Column('lado_jogador_preto', sa.String(length=36), nullable=False),
    sa.Column('historico_lances', sa.JSON(), nullable=False),
    sa.Column('condicao_fim', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('moves',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('san', sa.String(length=20), nullable=False),
    sa.Column('fen_resultante', sa.Text(), nullable=False),
    sa.Column('jogador', sa.String(length=36), nullable=False),
    sa.Column('numero_lance', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    op.drop_table('games')
    # ### end Alembic commands ###
